version: 2
jobs:
  build_and_test:
    working_directory: ~/projects/nishopping
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker run (mysql)
          command: |
            set -x
            cd ./docker
            docker-compose up -d
            sleep 30
            docker ps

      - run:
          name: test
          command: |
            cd ./backend
            mvn package

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test