version: 2
jobs:
  build_and_test:
    working_directory: ~/projects/nishopping
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    environment:
      - environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://contacts:3306/iv_shopping?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker run (mysql)
          command: |
            set -x
            cd ./docker
            docker-compose up -d

      - run:
          name: test
          command: |
            cd ./backend
            mvn package

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test