# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # run tests!
      - run:
        name: Generate cumulative pom.xml checksum
        command: |
          cd ./backend
          find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
          sort -o ~/pom-checksum ~/pom-checksum.tmp
        when: always

      - run: mvn clean test

