version: '3.1'

services:
  contacts:
    image: mysql:5.7
    container_name: contacts
    environment:
      MYSQL_DATABASE: 'iv_shopping'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_USER: 'ivis'
      MYSQL_PASSWORD: 'ivis_password'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3310:3306'
